# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_Q0gnb0 <- function(phi, theta, tol = 2.220446e-16) {
    .Call(`_sarima_arma_Q0gnb0`, phi, theta, tol)
}

arma_Q0gnb <- function(phi, theta, tol = 2.220446e-16) {
    .Call(`_sarima_arma_Q0gnb`, phi, theta, tol)
}

uniKalmanLikelihood0b <- function(y, mod, nit, op, update) {
    .Call(`_sarima_uniKalmanLikelihood0b`, y, mod, nit, op, update)
}

DAcvfWrtMA <- function(x) {
    .Call(`_sarima_DAcvfWrtMA`, x)
}

MAacvf0 <- function(x) {
    .Call(`_sarima_MAacvf0`, x)
}

